#!/bin/bash
set -e
set -o pipefail

if [ "x$1" = "xreplica" ]; then
    CYRUS_PREFIX="$CYRUSREPLICA_PREFIX"
    shift
elif [ "x$1" = "xmurder" ]; then
    CYRUS_PREFIX="$CYRUSMURDER_PREFIX"
    shift
else
    CYRUS_PREFIX="$CYRUSDEFAULT_PREFIX"
fi

if [ -z "$CYRUS_PREFIX" ]; then
    echo "Please set environment variables to match your cassandane.ini:" 1>&2
    echo "    CASS_ROOTDIR is currently '$CASS_ROOTDIR'" 1>&2
    echo "    CYRUSDEFAULT_PREFIX is currently '$CYRUSDEFAULT_PREFIX'" 1>&2
    echo "    CYRUSREPLICA_PREFIX is currently '$CYRUSREPLICA_PREFIX'" 1>&2
    echo "    CYRUSMURDER_PREFIX is currently  '$CYRUSMURDER_PREFIX'" 1>&2
    exit 1
fi

test ! -x configure -o configure.ac -nt configure && autoreconf -i -s

./configure CFLAGS="-g -O0 -Wall -Wextra -Werror -Wl,--as-needed $CFLAGS" \
    --prefix="$CYRUS_PREFIX" \
    --enable-http \
    --enable-unit-tests \
    --enable-replication \
    --with-openssl=yes \
    --enable-nntp \
    --enable-murder \
    --enable-idled \
    --enable-event-notification \
    --enable-sieve \
    --enable-autocreate \
    --enable-silent-rules \
    --enable-backup \
    --with-lmdb \
    $*

make lex-fix
