#!/usr/bin/env perl

use warnings;
use strict;

use File::Basename;
use File::Find;

no warnings 'File::Find';

my @prefixes = (
    @ENV{qw( CYRUSDEFAULT_PREFIX
             CYRUSMURDER_PREFIX
             CYRUSREPLICA_PREFIX )},
    glob "/cyrus/*"
);

sub master_version
{
    return if basename($_) ne 'master';
    return if not -x $_;

    system $_, q{-V};
}

my $whitespace = q{};
foreach my $p (grep { -d } @prefixes) {
    print "$whitespace\033[1m$p:\033[0m\n";

    find({ wanted => \&master_version, no_chdir => 1 }, $p);

    $whitespace = qq{\n};
}
