#!/bin/bash
set -e
set -o pipefail

if [ "x$1" = "xother" ]; then
    CYRUS_PREFIX="$CYRUSOTHER_PREFIX"
    shift
else
    CYRUS_PREFIX="$CYRUSDEFAULT_PREFIX"
fi

if [ -z "$CYRUS_PREFIX" ]; then
    echo "Please set environment variables to match your cassandane.ini:" 1>&2
    echo "    CASS_ROOTDIR is currently '$CASS_ROOTDIR'" 1>&2
    echo "    CYRUSDEFAULT_PREFIX is currently '$CYRUSDEFAULT_PREFIX'" 1>&2
    echo "    CYRUSOTHER_PREFIX is currently '$CYRUSOTHER_PREFIX'" 1>&2
    exit 1
fi

test ! -x configure -o configure.ac -nt configure && autoreconf -i -s

./configure \
    PATH="$PATH:/usr/local/cyruslibs/bin" \
    CFLAGS="-g -O0 -Wall -Wextra -Wformat-security -Werror -Wl,--as-needed -fstack-protector-strong -fstack-clash-protection $CFLAGS" \
    CXXFLAGS="-g -O0 -Wall -Wextra -Wformat-security -Werror -fstack-protector-strong -fstack-clash-protection $CXXFLAGS" \
    --prefix="$CYRUS_PREFIX" \
    --disable-http \
    --disable-calalarmd \
    --enable-unit-tests \
    --disable-replication \
    --with-openssl=yes \
    --disable-nntp \
    --disable-murder \
    --disable-idled \
    --disable-event-notification \
    --disable-sieve \
    --disable-autocreate \
    --enable-silent-rules \
    --disable-backup \
    --without-lmdb \
    --disable-xapian \
    --disable-jmap \
    --without-ldap \
    --enable-debug-slowio \
    --with-sqlite \
    $*

make lex-fix
