#!/bin/bash
set -e
set -o pipefail

CL_PATH="/usr/local"
CL_SYMLINK="$CL_PATH/cyruslibs"
CL_VPREFIX="cyruslibs-fastmail-v"

if [ -n "$1" ]; then
    CL_VERSION="$CL_VPREFIX$1"
    CL_PREFIX="$CL_PATH/$CL_VERSION"

    # check that /usr/local/cyruslibs is either nonexistent or a symlink
    if [ -e "$CL_SYMLINK" -a ! -L "$CL_SYMLINK" ]; then
        echo "$CL_SYMLINK is not a symlink"
        exit 1
    fi

    # check that the requested cyruslibs version is installed
    if [ ! -e "$CL_PREFIX" ]; then
        echo "$CL_VERSION is not installed"
        exit 2
    fi

    # remove the previous symlink
    test -L "$CL_SYMLINK" && sudo rm "$CL_SYMLINK"

    # link /usr/local/cyruslibs to the requested cyruslibs version
    sudo ln -s "$CL_PREFIX" "$CL_SYMLINK"
else
    ls -d $CL_PATH/$CL_VPREFIX* | cat
fi

stat --format '%N' "$CL_SYMLINK"
