#!/bin/bash
set -e
set -o pipefail

CL_SYMLINK="/usr/local/cyruslibs"

if [ -n "$1" ]; then
    CL_VERSION="cyruslibs-fastmail-v$1"
    CL_PREFIX="/usr/local/$CL_VERSION"

    # check that /usr/local/cyruslibs is either nonexistent or a symlink
    if [ -e "$CL_SYMLINK" -a ! -L "$CL_SYMLINK" ]; then
        echo "$CL_SYMLINK is not a symlink"
        exit 1
    fi

    # check that the requested cyruslibs version is installed
    if [ ! -e "$CL_PREFIX" ]; then
        echo "$CL_VERSION is not installed"
        exit 2
    fi

    # remove the previous symlink
    test -L "$CL_SYMLINK" && sudo rm "$CL_SYMLINK"

    # link /usr/local/cyruslibs to the requested cyruslibs version
    sudo ln -s "$CL_PREFIX" "$CL_SYMLINK"
fi

stat --format '%N' "$CL_SYMLINK"
